"""create workout sessions tables

Идентификатор ревизии: 0cc5089a8e01
Предыдущая ревизия: b80e0336146c
Дата создания: 2026-05-07 23:27:24.001552
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0cc5089a8e01'
down_revision: Union[str, None] = 'b80e0336146c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'completed' AND completed_at IS NOT NULL) OR (status IN ('in_progress', 'cancelled') AND completed_at IS NULL)", name='ck_workout_sessions_completed_at_consistency'),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'cancelled')", name='ck_workout_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_workout_id'), 'workout_sessions', ['workout_id'], unique=False)
    op.create_index('uq_workout_sessions_one_active_per_user', 'workout_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_table('workout_session_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('client_event_id', sa.UUID(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reps > 0', name='ck_workout_session_sets_reps_positive'),
    sa.CheckConstraint('set_index > 0', name='ck_workout_session_sets_set_index_positive'),
    sa.CheckConstraint('weight_kg >= 0', name='ck_workout_session_sets_weight_non_negative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'client_event_id', name='uq_workout_session_sets_client_event'),
    sa.UniqueConstraint('session_id', 'exercise_id', 'set_index', name='uq_workout_session_sets_position')
    )
    op.create_index(op.f('ix_workout_session_sets_exercise_id'), 'workout_session_sets', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_session_sets_session_id'), 'workout_session_sets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_session_sets_session_id'), table_name='workout_session_sets')
    op.drop_index(op.f('ix_workout_session_sets_exercise_id'), table_name='workout_session_sets')
    op.drop_table('workout_session_sets')
    op.drop_index('uq_workout_sessions_one_active_per_user', table_name='workout_sessions', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_index(op.f('ix_workout_sessions_workout_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
