"""exercise equipment list and media table

Идентификатор ревизии: 34bd6d03cfbc
Предыдущая ревизия: c06ec3502bcd
Дата создания: 2026-06-05 15:53:27.486912
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



revision: str = '34bd6d03cfbc'
down_revision: Union[str, None] = 'c06ec3502bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_exercise_media_position_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'position', name='uq_exercise_media_position')
    )
    op.create_index(op.f('ix_exercise_media_exercise_id'), 'exercise_media', ['exercise_id'], unique=False)
    op.alter_column(
        'exercises',
        'equipment',
        existing_type=sa.VARCHAR(length=120),
        type_=postgresql.ARRAY(sa.String(length=120)),
        postgresql_using='ARRAY[equipment]::varchar(120)[]',
        server_default='{}',
        existing_nullable=False,
    )
    op.execute(
        """
        INSERT INTO exercise_media (id, exercise_id, object_key, media_type, position, created_at, updated_at)
        SELECT gen_random_uuid(), id, media_object_key, media_type, 1, now(), now()
        FROM exercises
        WHERE media_object_key IS NOT NULL AND media_type IS NOT NULL
        """
    )

    op.drop_column('exercises', 'media_type')
    op.drop_column('exercises', 'media_object_key')
    op.drop_constraint('ck_exercises_primary_muscle_groups_not_empty', 'exercises', type_='check')
    op.alter_column(
        'exercises',
        'primary_muscle_groups',
        existing_type=postgresql.ARRAY(sa.String(length=50)),
        server_default='{}',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'exercises',
        'primary_muscle_groups',
        existing_type=postgresql.ARRAY(sa.String(length=50)),
        server_default=None,
        existing_nullable=False,
    )
    op.create_check_constraint(
        'ck_exercises_primary_muscle_groups_not_empty',
        'exercises',
        'cardinality(primary_muscle_groups) >= 1',
    )
    op.add_column('exercises', sa.Column('media_object_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('media_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE exercises
        SET media_object_key = em.object_key, media_type = em.media_type
        FROM exercise_media em
        WHERE em.exercise_id = exercises.id AND em.position = 1
        """
    )

    op.alter_column(
        'exercises',
        'equipment',
        existing_type=postgresql.ARRAY(sa.String(length=120)),
        type_=sa.VARCHAR(length=120),
        postgresql_using="COALESCE(equipment[1], '')",
        server_default=None,
        existing_nullable=False,
    )

    op.drop_index(op.f('ix_exercise_media_exercise_id'), table_name='exercise_media')
    op.drop_table('exercise_media')
    # ### end Alembic commands ###
