"""make exercise equipment required

Идентификатор ревизии: 4d0f10716393
Предыдущая ревизия: eee2a971ccb9
Дата создания: 2026-04-19 17:30:07.062610
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4d0f10716393'
down_revision: Union[str, None] = 'eee2a971ccb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'equipment',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'equipment',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
