"""add profile fields to users

Идентификатор ревизии: 5109d6a0dd31
Предыдущая ревизия: 525bfcdb6b29
Дата создания: 2026-05-09 12:24:50.623024
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5109d6a0dd31'
down_revision: Union[str, None] = '525bfcdb6b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
