"""add user avatar url

Идентификатор ревизии: 525bfcdb6b29
Предыдущая ревизия: 0cc5089a8e01
Дата создания: 2026-05-08 23:30:07.976436
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '525bfcdb6b29'
down_revision: Union[str, None] = '0cc5089a8e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
