"""add workouts series_id

Идентификатор ревизии: 71875aca7b62
Предыдущая ревизия: f9e86cc80cf4
Дата создания: 2026-06-12 05:50:15.138064
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '71875aca7b62'
down_revision: Union[str, None] = 'f9e86cc80cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('series_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workouts_series_id'), 'workouts', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_series_id'), table_name='workouts')
    op.drop_column('workouts', 'series_id')
    # ### end Alembic commands ###
