"""create workouts table

Идентификатор ревизии: 82e1b883d444
Предыдущая ревизия: 20260411_0001
Дата создания: 2026-04-14 12:49:20.134863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '82e1b883d444'
down_revision: Union[str, None] = '20260411_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_planned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('planned_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_planned = true AND planned_for IS NOT NULL) OR (is_planned = false AND planned_for IS NULL)', name='ck_workouts_planned_for_consistency'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_planned_for'), 'workouts', ['planned_for'], unique=False)
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_planned_for'), table_name='workouts')
    op.drop_table('workouts')
    # ### end Alembic commands ###
