"""create user_exercise_favorites

Идентификатор ревизии: 9e99f0dfd8f5
Предыдущая ревизия: f38e2e24a2bb
Дата создания: 2026-06-23 11:02:20.742663
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9e99f0dfd8f5'
down_revision: Union[str, None] = 'f38e2e24a2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercise_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_user_exercise_favorites_user_exercise')
    )
    op.create_index(op.f('ix_user_exercise_favorites_exercise_id'), 'user_exercise_favorites', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_favorites_user_id'), 'user_exercise_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_exercise_favorites_user_id'), table_name='user_exercise_favorites')
    op.drop_index(op.f('ix_user_exercise_favorites_exercise_id'), table_name='user_exercise_favorites')
    op.drop_table('user_exercise_favorites')
    # ### end Alembic commands ###
