"""add user metrics fields

Идентификатор ревизии: b80e0336146c
Предыдущая ревизия: 4d0f10716393
Дата создания: 2026-04-22 23:39:54.599761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b80e0336146c'
down_revision: Union[str, None] = '4d0f10716393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_weeks', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('weekly_volume_tons', sa.Numeric(precision=10, scale=1), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_volume_tons')
    op.drop_column('users', 'streak_weeks')
    # ### end Alembic commands ###
