"""add exercise media fields

Идентификатор ревизии: c06ec3502bcd
Предыдущая ревизия: a1b2c3d4e5f6
Дата создания: 2026-05-29 18:30:08.743233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c06ec3502bcd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('media_object_key', sa.String(length=1024), nullable=True))
    op.add_column('exercises', sa.Column('media_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'media_type')
    op.drop_column('exercises', 'media_object_key')
    # ### end Alembic commands ###
