"""change notification enabled default to false

Идентификатор ревизии: e295b4293004
Предыдущая ревизия: e33683c90639
Дата создания: 2026-05-25 17:09:05.675237
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e295b4293004'
down_revision: Union[str, None] = 'e33683c90639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notification_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_notification_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###
