"""add notification tables

Идентификатор ревизии: e33683c90639
Предыдущая ревизия: 9a509fd4ada5
Дата создания: 2026-05-21 23:00:32.498963
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e33683c90639'
down_revision: Union[str, None] = '9a509fd4ada5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_subscriptions_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sound', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('vibration', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('do_not_disturb', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reminders', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reminder_offset_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reminder_offset_minutes >= 0 AND reminder_offset_minutes <= 1440', name='ck_user_notification_settings_offset_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workout_notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workout_id', 'remind_at', name='uq_workout_notification_logs_unique')
    )
    op.create_index(op.f('ix_workout_notification_logs_remind_at'), 'workout_notification_logs', ['remind_at'], unique=False)
    op.create_index(op.f('ix_workout_notification_logs_user_id'), 'workout_notification_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_notification_logs_workout_id'), 'workout_notification_logs', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_notification_logs_workout_id'), table_name='workout_notification_logs')
    op.drop_index(op.f('ix_workout_notification_logs_user_id'), table_name='workout_notification_logs')
    op.drop_index(op.f('ix_workout_notification_logs_remind_at'), table_name='workout_notification_logs')
    op.drop_table('workout_notification_logs')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
