"""drop stored user metrics columns

Идентификатор ревизии: ea671cf825d7
Предыдущая ревизия: 34bd6d03cfbc
Дата создания: 2026-06-06 07:54:55.546100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ea671cf825d7'
down_revision: Union[str, None] = '34bd6d03cfbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'streak_weeks')
    op.drop_column('users', 'weekly_volume_tons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weekly_volume_tons', sa.NUMERIC(precision=10, scale=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('streak_weeks', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
