"""create exercises and workout_exercises tables

Идентификатор ревизии: eee2a971ccb9
Предыдущая ревизия: 82e1b883d444
Дата создания: 2026-04-15 23:06:13.764251
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'eee2a971ccb9'
down_revision: Union[str, None] = '82e1b883d444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('muscle_groups', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('equipment', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cardinality(muscle_groups) > 0', name='ck_exercises_muscle_groups_not_empty'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_user_id', 'name', name='uq_exercises_owner_name')
    )
    op.create_index(op.f('ix_exercises_created_by_user_id'), 'exercises', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_index > 0', name='ck_workout_exercises_order_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id'),
    sa.UniqueConstraint('workout_id', 'order_index', name='uq_workout_exercises_workout_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_by_user_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
