"""create workout templates tables

Идентификатор ревизии: f38e2e24a2bb
Предыдущая ревизия: 71875aca7b62
Дата создания: 2026-06-22 17:14:19.336483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f38e2e24a2bb'
down_revision: Union[str, None] = '71875aca7b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_user_id', 'title', name='uq_workout_templates_owner_title')
    )
    op.create_index(op.f('ix_workout_templates_created_by_user_id'), 'workout_templates', ['created_by_user_id'], unique=False)
    op.create_table('user_workout_template_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_template_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workout_template_id', name='uq_user_workout_template_favorites_user_template')
    )
    op.create_index(op.f('ix_user_workout_template_favorites_user_id'), 'user_workout_template_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_workout_template_favorites_workout_template_id'), 'user_workout_template_favorites', ['workout_template_id'], unique=False)
    op.create_table('workout_template_exercises',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_index > 0', name='ck_workout_template_exercises_order_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'exercise_id'),
    sa.UniqueConstraint('template_id', 'order_index', name='uq_workout_template_exercises_template_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_template_exercises')
    op.drop_index(op.f('ix_user_workout_template_favorites_workout_template_id'), table_name='user_workout_template_favorites')
    op.drop_index(op.f('ix_user_workout_template_favorites_user_id'), table_name='user_workout_template_favorites')
    op.drop_table('user_workout_template_favorites')
    op.drop_index(op.f('ix_workout_templates_created_by_user_id'), table_name='workout_templates')
    op.drop_table('workout_templates')
    # ### end Alembic commands ###
