"""create guide tables

Идентификатор ревизии: f9e86cc80cf4
Предыдущая ревизия: ea671cf825d7
Дата создания: 2026-06-10 17:15:25.331309
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f9e86cc80cf4'
down_revision: Union[str, None] = 'ea671cf825d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_object_key', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_guide_categories_position_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position', name='uq_guide_categories_position')
    )
    op.create_index(op.f('ix_guide_categories_name'), 'guide_categories', ['name'], unique=False)
    op.create_table('guide_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guide_category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_object_key', sa.String(length=1024), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('views_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position > 0', name='ck_guide_articles_position_positive'),
    sa.CheckConstraint('reading_time_minutes >= 0', name='ck_guide_articles_reading_time_non_negative'),
    sa.CheckConstraint('views_count >= 0', name='ck_guide_articles_views_non_negative'),
    sa.ForeignKeyConstraint(['guide_category_id'], ['guide_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_category_id', 'position', name='uq_guide_articles_category_position')
    )
    op.create_index(op.f('ix_guide_articles_guide_category_id'), 'guide_articles', ['guide_category_id'], unique=False)
    op.create_index(op.f('ix_guide_articles_title'), 'guide_articles', ['title'], unique=False)
    op.create_index(op.f('ix_guide_articles_views_count'), 'guide_articles', ['views_count'], unique=False)
    op.create_table('user_guide_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('guide_article_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guide_article_id'], ['guide_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'guide_article_id', name='uq_user_guide_favorites_user_article')
    )
    op.create_index(op.f('ix_user_guide_favorites_guide_article_id'), 'user_guide_favorites', ['guide_article_id'], unique=False)
    op.create_index(op.f('ix_user_guide_favorites_user_id'), 'user_guide_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_guide_favorites_user_id'), table_name='user_guide_favorites')
    op.drop_index(op.f('ix_user_guide_favorites_guide_article_id'), table_name='user_guide_favorites')
    op.drop_table('user_guide_favorites')
    op.drop_index(op.f('ix_guide_articles_views_count'), table_name='guide_articles')
    op.drop_index(op.f('ix_guide_articles_title'), table_name='guide_articles')
    op.drop_index(op.f('ix_guide_articles_guide_category_id'), table_name='guide_articles')
    op.drop_table('guide_articles')
    op.drop_index(op.f('ix_guide_categories_name'), table_name='guide_categories')
    op.drop_table('guide_categories')
    # ### end Alembic commands ###
