"""add workout exercise target sets

Идентификатор ревизии: fdb5307c3980
Предыдущая ревизия: e295b4293004
Дата создания: 2026-05-26 06:21:06.037617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'fdb5307c3980'
down_revision: Union[str, None] = 'e295b4293004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercise_target_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('set_index > 0', name='ck_workout_exercise_target_sets_set_index_positive'),
    sa.CheckConstraint('target_reps IS NULL OR target_reps > 0', name='ck_workout_exercise_target_sets_reps_positive'),
    sa.CheckConstraint('target_weight_kg IS NULL OR target_weight_kg >= 0', name='ck_workout_exercise_target_sets_weight_non_negative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'exercise_id', 'set_index', name='uq_workout_exercise_target_sets_position')
    )
    op.create_index(op.f('ix_workout_exercise_target_sets_exercise_id'), 'workout_exercise_target_sets', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercise_target_sets_workout_id'), 'workout_exercise_target_sets', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_target_sets_workout_id'), table_name='workout_exercise_target_sets')
    op.drop_index(op.f('ix_workout_exercise_target_sets_exercise_id'), table_name='workout_exercise_target_sets')
    op.drop_table('workout_exercise_target_sets')
    # ### end Alembic commands ###
